### ISSUE TITLE
Färgschema

### ISSUE THREAD

**Issue by seetee** [tcstenungsund/sark2024#1]
Analysera befintlig webbplats, se över konkurrenter och trender (årets färger, och liknande). Referera till moodboarden. Se till att ha en ordentlig förståelse för 60:30:10-principen. Kontrollera a11y, kontrast och vilka toner av valde färger som skall användas.

**Comment by Gustafpieper** [comment]
[Färgschema.docx](https://github.com/tcstenungsund/sark2024/files/14496305/Fargschema.docx)



![Image](https://github.com/tcstenungsund/sark2024/assets/113342781/e41ce61a-72cf-42be-94f0-a03acd2a7426)

![Image](https://github.com/tcstenungsund/sark2024/assets/113342781/396cf215-af1e-409f-8170-d2f2bef2432a)

![Image](https://github.com/tcstenungsund/sark2024/assets/113342781/721ba5ba-3a2e-4645-8cd2-9f8d16f2c10d)

**Comment by LinusRhoden** [comment]
Vilka färger ska vi använda till h och p?
