### ISSUE TITLE
Definiera content types

### ISSUE THREAD

**Issue by seetee** [tcstenungsund/sark2024#12]
Analysera den befintliga webbplatsen. Vad finns för innehåll? Hur kan man kategorisera innehållet? Hur skall innehållet visas på sidan och hur skall det läggas till av användarna? Finns det snarlikt innehåll som kan slås samman till ett, till exempel kan "utflykter" och "utbildningskvällar" slås ihop till "Events"? Kan "för nybörjare" och "länktips" slås ihop till "Utbildning"?

Fundera också på vilka fields som hör till varje content type. Skall man kunna lägga till 1 eller fler bilder? Måste man lägga till en bild? Vill man ha både en rubrik och en obligatorisk ingress, så man kan visa lite mer info på förstasidan, utan att behöva visa hela artikeln? Skall datum och plats finnas med, och hur matar man in det i så fall?

Anteckna allt detta i dokumentationen.

**Comment by lucasjorstun2005** [comment]
## Artiklar/Aktiviteter:

>Både nyheter, blog posts, aktiviteter. Innehåller rubrik, datum, brödtext. Du kan märka den som viktig, vilket gör att den visas högt upp i flödet, om den är märkt som viktig, behöver man också lägga in hur länge man vill att den ska ligga uppe som viktig. Om den inte är märkt som viktig behöver man inte lägga in hur länge den ska vara uppe. Möjlighet att lägga till olika taggar.

## Bilder:

>En bild som en content type så att man enkelt kan ladda upp en bild vart man vill ha den, år när bilden togs. Om möjligt exakt datum, plats, och vem som tog bilden
