### ISSUE TITLE
Skapa en datamigrerings HOWTO

### ISSUE THREAD

**Issue by seetee** [tcstenungsund/sark2024#17]
Då content types och taxonomies är på plats och alla fields vid "Add content" är kontrollerad och hela processen är smidig, skapa data-migrering.md i er dokumenation. Fyll detta dokument med en steg-för-steg-instruktion i hur man migrerar data från gamla sidan till dev-servern.

**Comment by HugoOskarsson05** [comment]
- [ ] Loggan ska kopieras och läggas in i den nya sidan
- [ ] data ansvariga skall kopiera in alla artiklar. Kopiera all text och även alla bilder och lägg över dem till den nya sidan.
- [ ] Kopiera in länken till deras facebook och lägg dem i footern. 
- [ ] Ta snabb länkarna och kopiera in dem i footern.	
- [ ] Ta det stora fotoalbumet och lägg över alla bilder till content typen bilder.
- [ ]
