### ISSUE TITLE
 Ny logotyp

### ISSUE THREAD

**Issue by seetee** [tcstenungsund/sark2024#3]
- [x] Se över den befintliga logotypen. Behövs en ny? Räcker det att förnya den gamla, eller är det bättre att göra en helt ny? Vad skall inspirationen till den nya vara, i så fall? 
- [x] Använd rätt färger. Oavsett om det blir en uppdatering eller en helt ny så skall logotypen följa ert valda färgtema. Se till att den fungerar även i svart/vitt samt att färgerna håller bra kontrast. 
- [x] Sikta på att supporta tre stolekar; favicon, fyrkantig avatar-storlek samt stor headerlogotype. Antingen kan designen fungera för alla tre, eller så får det tas fram mer och mindre komplexa varianter. Prototypa med wireframes. 
- [x] Bygg i Inkscape!
- [x] Användartester

**Comment by samuelhubinette** [comment]
![Image](https://github.com/tcstenungsund/sark2024/assets/113342404/f8137e32-55ca-4a38-a613-e10ec1c2d51e)

**Comment by samuelhubinette** [comment]
favicon loggan

**Comment by AlvinAhl** [comment]
![Webbutveckling Radiologga](https://github.com/tcstenungsund/sark2024/assets/125873667/86343de0-d5b8-4d51-bbcc-a1e12d642df5)
<img width="197" alt="Skärmbild 2024-03-19 142917" src="https://github.com/tcstenungsund/sark2024/assets/125873667/ea7ebba3-2fe7-463a-81ba-a14e6683f7a2">

**Comment by samuelhubinette** [comment]
Jag gjorde favicon loggan :)

**Comment by AlvinAhl** [comment]
![Image](https://github.com/tcstenungsund/sark2024/assets/125873667/abb92e18-9ade-40f7-b9ca-b80b13385424)

**Comment by AlvinAhl** [comment]
![Image](https://github.com/tcstenungsund/sark2024/assets/125873667/5746cf29-8e56-4e28-9d92-87daae68dce0)

**Comment by JoelAlderholm16** [comment]
![hej](https://github.com/tcstenungsund/sark2024/assets/136325516/d4b4d10a-0855-4461-90e8-1b1954c857d4)

**Comment by JoelAlderholm16** [comment]
![hej](https://github.com/tcstenungsund/sark2024/assets/136325516/7eda4f0c-09f2-4862-a659-313cfa817edc)

**Comment by AlexanderTorkar** [comment]
![Image](https://github.com/tcstenungsund/sark2024/assets/113342138/6d6f3fae-acb0-4720-8ace-0318c38dda91)

**Comment by AlexanderTorkar** [comment]
[file:///C:/Users/05alto26/footerny4r.svg](url)
