### ISSUE TITLE
create design comp för artikel/artikklar

### ISSUE THREAD

**Issue by EbbeJohansson04** [tcstenungsund/sark2024#36]
Gör en design comp för hur artiklarna på sidan ska se ut med combinationer av  text, bilder, underrubriket osv.

Ska ej blandas ihop med hemsidans samlingsflik för "Artiklar"

**Comment by LinusRhoden** [comment]
Länk till figma: https://www.figma.com/design/ukNn7qc03EkWAE6OE5Lsao/Design-Comp?node-id=0%3A1&t=qAuGRf9qehKpHGZx-1





![Image](https://github.com/tcstenungsund/sark2024/assets/113342302/fff58a57-b3a3-44e4-868c-0ebb7b00b332)
