### ISSUE TITLE
Fonter

### ISSUE THREAD

**Issue by seetee** [tcstenungsund/sark2024#4]
Analysera befintlig webbsida, se över konkurrenternas fontval och se vad trenderna just nu är (nya fonter, årets font, etc.).

Se till att upphovsrätten efterlevs. Välj 1 eller som mest 2 fonter. Definiera vilken fontstorlek ([fluid type scale](https://www.fluid-type-scale.com/)) olika rubriker och brödtext skall ha.

**Comment by EbbeJohansson04** [comment]
Förslag på preliminära fonts att använda är Roboto för rubriker och titlar medan Lato används för brödtext, underrubriker osv.

Länk för att visa utseende:
https://typ.io/fonts/lato/with/roboto

**Comment by luckelc** [comment]
Tycker dem ser bra ut, glöm inte att definiera fontstorlek för de olika typerna.

**Comment by EbbeJohansson04** [comment]
förslak på fonternas respektive storlekar.

Roboto: h1 = 2.25em, h2 = 1.75em, h3 = 1.42em, h4 = 1.25em, h5 = 1.08em, h6 = 1em

Lato: p-taggar med storleken 1.4em.
