### ISSUE TITLE
Skapa moodboard

### ISSUE THREAD

**Issue by seetee** [tcstenungsund/sark2024#6]
Analysera befintlig webbplats samt konkurrenter. Vad är syftet med sidan? Vilken känsla vill förmedlas? Skapa en moodboard, antingen fysiskt eller digitalt.

**Comment by Ad4msvensson** [comment]
![Image](https://github.com/tcstenungsund/sark2024/assets/125870991/a5f4b3fa-ae96-4789-8d8e-a7c2afdea37c)
