### ISSUE TITLE
Skapa wireframes

### ISSUE THREAD

**Issue by seetee** [tcstenungsund/sark2024#9]
Analysera innehållet på befintlig webbplats. Vilka sorters innehåll finns och hur skall det organiseras. Samråd med Data och de som arbetar med Content types / Taxonomies. Det behövs en wireframe för förstasidan samt en för varje content type. 

- [x] Wireframe för förstasidan 
- [x] Wireframe för varje content type

**Comment by luckelc** [comment]
![wireframe_content_type](https://github.com/tcstenungsund/sark2024/assets/98053131/6e76eca1-056e-4b9d-a555-c92e25e25437)
![wireframe_frontpage](https://github.com/tcstenungsund/sark2024/assets/98053131/62835ff8-89ca-406a-bbfe-2cee4ed525a5)
